# Generated by Django 5.1.2 on 2024-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0002_temas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='tema',
            field=models.CharField(choices=[('Normativas y Legislaciones', 'Normativas y Legislaciones'), ('Informes sectoriales y de mercado', 'Informes sectoriales y de mercado'), ('Patentes', 'Patentes'), ('Eventos y Seminarios', 'Eventos y Seminarios'), ('Publicaciones Cientificas', 'Publicaciones Cientificas'), ('Noticias Comerciales', 'Noticias Comerciales'), ('Blogs', 'Blogs'), ('Fuentes Sindicadas', 'Fuentes Sindicadas'), ('Estudios de Vigilancia y Prospectiva', 'Estudios de Vigilancia y Prospectiva')], max_length=100),
        ),
    ]
