# Generated by Django 5.1.2 on 2024-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0003_alter_temas_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='region',
            field=models.CharField(choices=[('Región Metropolitana', 'Región Metropolitana'), ('Valparaíso', 'Valparaíso'), ('Biobío', 'Biobío'), ('Los Lagos', 'Los Lagos'), ('Araucanía', 'Araucanía'), ('Coquimbo', 'Coquimbo'), ('Antofagasta', 'Antofagasta'), ('O´Higgins', 'O´Higgins'), ('Maule', 'Maule'), ('Atacama', 'Atacama'), ('Los Ríos', 'Los Ríos'), ('Ñuble', 'Ñuble'), ('Tarapacá', 'Tarapacá'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes'), ('Arica y Parinacota', 'Arica y Parinacota')], max_length=100),
        ),
    ]
