# Generated by Django 5.1.2 on 2024-11-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0004_alter_temas_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas',
            old_name='info',
            new_name='informacion',
        ),
    ]
