# Generated by Django 5.1.2 on 2024-11-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
