# Generated by Django 5.1.2 on 2024-11-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0005_delete_customuser'),
        ('vigifia_app', '0005_rename_info_temas_informacion'),
    ]

    operations = [
    ]
