# Generated by Django 5.1.2 on 2024-11-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0006_merge_20241126_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temas',
        ),
    ]
