# Generated by Django 5.1.2 on 2025-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigifia_app', '0009_alter_fuenteexterna_archivo_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuenteexterna',
            name='contenido',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
