# Generated by Django 5.1.2 on 2024-10-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='boletines/')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Cambio climático', 'Cambio climático'), ('Recursos hídricos', 'Recursos hídricos'), ('Sistemas alimentarios', 'Sistemas alimentarios')], max_length=40)),
                ('ubicacion', models.CharField(choices=[('Región Metropolitana', 'Región Metropolitana'), ('Valparaíso', 'Valparaíso'), ('Biobío', 'Biobío'), ('Los Lagos', 'Los Lagos'), ('Araucanía', 'Araucanía'), ('Coquimbo', 'Coquimbo'), ('Antofagasta', 'Antofagasta'), ('O´Higgins', 'O´Higgins'), ('Maule', 'Maule'), ('Atacama', 'Atacama'), ('Los Ríos', 'Los Ríos'), ('Ñuble', 'Ñuble'), ('Tarapacá', 'Tarapacá'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes'), ('Arica y Parinacota', 'Arica y Parinacota')], max_length=50)),
            ],
        ),
    ]
